version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: [ "npm", "run", "dev" ]
    networks:
      - web3front

networks:
  web3front:
    driver: bridge
